services:
  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - 3214:3214
    volumes:
      - /mnt/user/documents/3d:/libraries
    environment:
      DATABASE_ADAPTER: postgresql # mysql2 or sqlite3 are also supported
      DATABASE_HOST: postgres-server
      DATABASE_NAME: manyfold # or the path to the database file if using sqlite3
      # TODO: Make env variable
      DATABASE_USER: manyfold
      # TODO: Make env variable
      DATABASE_PASSWORD: password
      DATABASE_URL: postgresql://manyfold:password@db/manyfold?pool=5
      SECRET_KEY_BASE: a_nice_long_random_string
      REDIS_URL: redis://redis:6379/1
      PUID: 1000
      PGID: 1000
      # For details of other optional environment variables, including features such
      # as multiuser mode, visit https://manyfold.app/sysadmin/configuration.html
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    labels:
      net.unraid.docker.icon: "./app.svg"
    links:
      - postgres
      - redis
    networks:
      - manyfold
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
  
  postgres:
    image: postgres:15
    volumes:
      - /mnt/user/appdata/manyfold_stack:/var/lib/postgresql/data
    environment:
      # TODO: Make env variable
      POSTGRES_USER: manyfold
      # TODO: Make env variable
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    networks:
      - manyfold

  redis:
    image: docker.io/library/redis:alpine
    restart: on-failure
    networks:
      - manyfold

networks:
  manyfold:
